# Generated by Django 4.1.5 on 2023-01-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome completo do proprietario')),
            ],
            options={
                'verbose_name': 'proprietario',
                'verbose_name_plural': 'proprietarios',
            },
        ),
    ]
