# Generated by Django 4.1.5 on 2023-01-04 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario', models.CharField(max_length=128, validators=[django.core.validators.MinValueValidator(limit_value=8, message='Nome registrado não corresponde ao valor minimo')], verbose_name='Nome do proprietario do veiculo')),
            ],
            options={
                'verbose_name': 'veiculo',
                'verbose_name_plural': 'veiculos',
            },
        ),
    ]
