# Generated by Django 4.1.5 on 2023-01-05 14:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil_app', '0001_initial'),
        ('Veiculo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='alugado',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Este campo tem por objetivo salvar o estado se foi alugado ou não'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(limit_value=4, message='Valor minimo especificado para o ano invalido, minimo 4')], verbose_name='Especifique o ano que o carro foi fabricado'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(max_length=128, null=True, verbose_name='Especifique a marca do carro'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Especifique o modelo do carro'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='proprietario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='veiculos', to='Perfil_app.perfil', verbose_name='Este campo proprietario é um campo O2O, '),
        ),
    ]
